name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        run: sudo apt-get update && sudo apt-get install -y openjdk-17-jdk

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV

      - name: Verify Java version
        run: java -version

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Generate HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        run: sudo apt-get update && sudo apt-get install -y openjdk-17-jdk

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV

      - name: Verify Java version
        run: java -version

      - name: Run Tests
        run: ./gradlew test

      - name: Generate HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: unit_test.report
          path: app/build/reports/tests/testDebugUnitTest/


  instrumentation-test:
    needs: [ unit-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        run: sudo apt-get update && sudo apt-get install -y openjdk-17-jdk

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV

      - name: Verify Java version
        run: java -version

      - name: Run espresso tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: Upload test Report
        uses: actions/upload-artifact@v4
        with:
          name: instrumentation_test.report
          path: app/build/reports/androidTests/connected/

