name: CI

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checar o código
        uses: actions/checkout@v4

      - name: Executar Lint
        uses: ./gradlew lintDebug

      - name: Gerar Relatório HTML
        uses: actions/upload-artifact@v4
        with:
          name: index.html
          path: app/build/reports/lint-results-debug.html

